// <auto-generated />
using System;
using FutManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FutManagement.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250624182858_SeedCountriesData")]
    partial class SeedCountriesData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FutManagement.Core.Entities.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FoundingYear")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TransferBudget")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("FutManagement.Core.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bf6"),
                            Code = "ARG",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Argentina",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bf7"),
                            Code = "FRA",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "France",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bf8"),
                            Code = "BRA",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Brazil",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bf9"),
                            Code = "ENG",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "England",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bfa"),
                            Code = "BEL",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Belgium",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bfb"),
                            Code = "CRO",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Croatia",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bfc"),
                            Code = "NED",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Netherlands",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bfd"),
                            Code = "ITA",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Italy",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bfe"),
                            Code = "POR",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Portugal",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bff"),
                            Code = "ESP",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Spain",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c00"),
                            Code = "MAR",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Morocco",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c01"),
                            Code = "SUI",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Switzerland",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c02"),
                            Code = "USA",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "USA",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c03"),
                            Code = "GER",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Germany",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c04"),
                            Code = "MEX",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Mexico",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c05"),
                            Code = "URU",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Uruguay",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c06"),
                            Code = "COL",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Colombia",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c07"),
                            Code = "DEN",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Denmark",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c08"),
                            Code = "SEN",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Senegal",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c09"),
                            Code = "JPN",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Japan",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c0a"),
                            Code = "PER",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Peru",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c0b"),
                            Code = "IRN",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Iran",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c0c"),
                            Code = "SRB",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Serbia",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c0d"),
                            Code = "POL",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Poland",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c0e"),
                            Code = "SWE",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sweden",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c0f"),
                            Code = "UKR",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Ukraine",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c10"),
                            Code = "WAL",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Wales",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c11"),
                            Code = "KOR",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "South Korea",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c12"),
                            Code = "AUS",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Australia",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c13"),
                            Code = "AUT",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Austria",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c14"),
                            Code = "HUN",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Hungary",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c15"),
                            Code = "NOR",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Norway",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c16"),
                            Code = "CZE",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Czechia",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c17"),
                            Code = "NGA",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Nigeria",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c18"),
                            Code = "TUR",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Turkey",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c19"),
                            Code = "ECU",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Ecuador",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c1a"),
                            Code = "SCO",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Scotland",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c1b"),
                            Code = "GRE",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Greece",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c1c"),
                            Code = "TUN",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tunisia",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c1d"),
                            Code = "MLI",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Mali",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c1e"),
                            Code = "ALG",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Algeria",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c1f"),
                            Code = "EGY",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Egypt",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c20"),
                            Code = "CIV",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Ivory Coast",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c21"),
                            Code = "CAN",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Canada",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c22"),
                            Code = "SVK",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Slovakia",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c23"),
                            Code = "ROU",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Romania",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c24"),
                            Code = "CMR",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Cameroon",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c25"),
                            Code = "VEN",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Venezuela",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c26"),
                            Code = "PAR",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Paraguay",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c27"),
                            Code = "SVN",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Slovenia",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("FutManagement.Core.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MarketValue")
                        .HasColumnType("numeric");

                    b.Property<Guid>("NationalityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nickname")
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("NationalityId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("FutManagement.Core.Entities.Club", b =>
                {
                    b.HasOne("FutManagement.Core.Entities.Country", "Country")
                        .WithMany("Clubs")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("FutManagement.Core.Entities.Player", b =>
                {
                    b.HasOne("FutManagement.Core.Entities.Club", "Club")
                        .WithMany("Players")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FutManagement.Core.Entities.Country", "Nationality")
                        .WithMany("Players")
                        .HasForeignKey("NationalityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Nationality");
                });

            modelBuilder.Entity("FutManagement.Core.Entities.Club", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("FutManagement.Core.Entities.Country", b =>
                {
                    b.Navigation("Clubs");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
