// <auto-generated />
using System;
using FutManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FutManagement.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FutManagement.Core.Entities.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FoundingYear")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TransferBudget")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("clubs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1a7b7b0-1b1a-4b9a-8b0a-0b9b8b0a0b0a"),
                            CountryId = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bf9"),
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            FoundingYear = 1886,
                            Name = "Arsenal",
                            TransferBudget = 150000000m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c1a7b7b0-1b1a-4b9a-8b0a-0b9b8b0a0b0b"),
                            CountryId = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bf9"),
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            FoundingYear = 1880,
                            Name = "Manchester City",
                            TransferBudget = 200000000m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c1a7b7b0-1b1a-4b9a-8b0a-0b9b8b0a0b0c"),
                            CountryId = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bf9"),
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            FoundingYear = 1878,
                            Name = "Manchester United",
                            TransferBudget = 180000000m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c1a7b7b0-1b1a-4b9a-8b0a-0b9b8b0a0b0d"),
                            CountryId = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bf9"),
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            FoundingYear = 1892,
                            Name = "Liverpool",
                            TransferBudget = 160000000m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c1a7b7b0-1b1a-4b9a-8b0a-0b9b8b0a0b0e"),
                            CountryId = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bf9"),
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            FoundingYear = 1905,
                            Name = "Chelsea",
                            TransferBudget = 170000000m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c1a7b7b0-1b1a-4b9a-8b0a-0b9b8b0a0b0f"),
                            CountryId = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bf9"),
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            FoundingYear = 1882,
                            Name = "Tottenham Hotspur",
                            TransferBudget = 120000000m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d1a7b7b0-1b1a-4b9a-8b0a-0b9b8b0a0b1a"),
                            CountryId = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bff"),
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            FoundingYear = 1902,
                            Name = "Real Madrid",
                            TransferBudget = 250000000m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d1a7b7b0-1b1a-4b9a-8b0a-0b9b8b0a0b1b"),
                            CountryId = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bff"),
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            FoundingYear = 1899,
                            Name = "Barcelona",
                            TransferBudget = 100000000m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d1a7b7b0-1b1a-4b9a-8b0a-0b9b8b0a0b1c"),
                            CountryId = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bff"),
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            FoundingYear = 1903,
                            Name = "Atlético Madrid",
                            TransferBudget = 130000000m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d1a7b7b0-1b1a-4b9a-8b0a-0b9b8b0a0b1d"),
                            CountryId = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bff"),
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            FoundingYear = 1890,
                            Name = "Sevilla",
                            TransferBudget = 80000000m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d1a7b7b0-1b1a-4b9a-8b0a-0b9b8b0a0b1e"),
                            CountryId = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bff"),
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            FoundingYear = 1909,
                            Name = "Real Sociedad",
                            TransferBudget = 70000000m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e1a7b7b0-1b1a-4b9a-8b0a-0b9b8b0a0b2a"),
                            CountryId = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c03"),
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            FoundingYear = 1900,
                            Name = "Bayern Munich",
                            TransferBudget = 180000000m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e1a7b7b0-1b1a-4b9a-8b0a-0b9b8b0a0b2b"),
                            CountryId = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c03"),
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            FoundingYear = 1909,
                            Name = "Borussia Dortmund",
                            TransferBudget = 120000000m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e1a7b7b0-1b1a-4b9a-8b0a-0b9b8b0a0b2c"),
                            CountryId = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c03"),
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            FoundingYear = 2009,
                            Name = "RB Leipzig",
                            TransferBudget = 100000000m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e1a7b7b0-1b1a-4b9a-8b0a-0b9b8b0a0b2d"),
                            CountryId = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c03"),
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            FoundingYear = 1904,
                            Name = "Bayer 04 Leverkusen",
                            TransferBudget = 90000000m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f1a7b7b0-1b1a-4b9a-8b0a-0b9b8b0a0b3a"),
                            CountryId = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bfd"),
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            FoundingYear = 1897,
                            Name = "Juventus",
                            TransferBudget = 120000000m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f1a7b7b0-1b1a-4b9a-8b0a-0b9b8b0a0b3b"),
                            CountryId = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bfd"),
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            FoundingYear = 1908,
                            Name = "Inter Milan",
                            TransferBudget = 140000000m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f1a7b7b0-1b1a-4b9a-8b0a-0b9b8b0a0b3c"),
                            CountryId = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bfd"),
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            FoundingYear = 1899,
                            Name = "AC Milan",
                            TransferBudget = 130000000m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f1a7b7b0-1b1a-4b9a-8b0a-0b9b8b0a0b3d"),
                            CountryId = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bfd"),
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            FoundingYear = 1926,
                            Name = "Napoli",
                            TransferBudget = 100000000m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f1a7b7b0-1b1a-4b9a-8b0a-0b9b8b0a0b3e"),
                            CountryId = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bfd"),
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            FoundingYear = 1927,
                            Name = "AS Roma",
                            TransferBudget = 90000000m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a1a7b7b0-1b1a-4b9a-8b0a-0b9b8b0a0b4a"),
                            CountryId = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bf7"),
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            FoundingYear = 1970,
                            Name = "Paris Saint-Germain",
                            TransferBudget = 220000000m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a1a7b7b0-1b1a-4b9a-8b0a-0b9b8b0a0b4b"),
                            CountryId = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bf7"),
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            FoundingYear = 1899,
                            Name = "Olympique de Marseille",
                            TransferBudget = 80000000m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a1a7b7b0-1b1a-4b9a-8b0a-0b9b8b0a0b4c"),
                            CountryId = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bf7"),
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            FoundingYear = 1924,
                            Name = "AS Monaco",
                            TransferBudget = 70000000m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a1a7b7b0-1b1a-4b9a-8b0a-0b9b8b0a0b4d"),
                            CountryId = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bf7"),
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            FoundingYear = 1950,
                            Name = "Olympique Lyonnais",
                            TransferBudget = 75000000m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b1a7b7b0-1b1a-4b9a-8b0a-0b9b8b0a0b5a"),
                            CountryId = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bf8"),
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            FoundingYear = 1895,
                            Name = "Flamengo",
                            TransferBudget = 50000000m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b1a7b7b0-1b1a-4b9a-8b0a-0b9b8b0a0b5b"),
                            CountryId = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bf8"),
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            FoundingYear = 1914,
                            Name = "Palmeiras",
                            TransferBudget = 60000000m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b1a7b7b0-1b1a-4b9a-8b0a-0b9b8b0a0b5c"),
                            CountryId = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bf8"),
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            FoundingYear = 1910,
                            Name = "Corinthians",
                            TransferBudget = 40000000m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b1a7b7b0-1b1a-4b9a-8b0a-0b9b8b0a0b5d"),
                            CountryId = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bf8"),
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            FoundingYear = 1930,
                            Name = "São Paulo",
                            TransferBudget = 35000000m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b1a7b7b0-1b1a-4b9a-8b0a-0b9b8b0a0b5e"),
                            CountryId = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bf8"),
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            FoundingYear = 1903,
                            Name = "Grêmio",
                            TransferBudget = 30000000m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c2a7b7b0-1b1a-4b9a-8b0a-0b9b8b0a0b6a"),
                            CountryId = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bf6"),
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            FoundingYear = 1901,
                            Name = "River Plate",
                            TransferBudget = 45000000m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c2a7b7b0-1b1a-4b9a-8b0a-0b9b8b0a0b6b"),
                            CountryId = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bf6"),
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            FoundingYear = 1905,
                            Name = "Boca Juniors",
                            TransferBudget = 42000000m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c2a7b7b0-1b1a-4b9a-8b0a-0b9b8b0a0b6c"),
                            CountryId = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bf6"),
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            FoundingYear = 1903,
                            Name = "Racing Club",
                            TransferBudget = 25000000m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("FutManagement.Core.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bf6"),
                            Code = "ARG",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Argentina",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bf7"),
                            Code = "FRA",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "France",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bf8"),
                            Code = "BRA",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Brazil",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bf9"),
                            Code = "ENG",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "England",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bfa"),
                            Code = "BEL",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Belgium",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bfb"),
                            Code = "CRO",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Croatia",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bfc"),
                            Code = "NED",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Netherlands",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bfd"),
                            Code = "ITA",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Italy",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bfe"),
                            Code = "POR",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Portugal",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6bff"),
                            Code = "ESP",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Spain",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c00"),
                            Code = "MAR",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Morocco",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c01"),
                            Code = "SUI",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Switzerland",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c02"),
                            Code = "USA",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "USA",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c03"),
                            Code = "GER",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Germany",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c04"),
                            Code = "MEX",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Mexico",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c05"),
                            Code = "URU",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Uruguay",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c06"),
                            Code = "COL",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Colombia",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c07"),
                            Code = "DEN",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Denmark",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c08"),
                            Code = "SEN",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Senegal",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c09"),
                            Code = "JPN",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Japan",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c0a"),
                            Code = "PER",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Peru",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c0b"),
                            Code = "IRN",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Iran",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c0c"),
                            Code = "SRB",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Serbia",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c0d"),
                            Code = "POL",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Poland",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c0e"),
                            Code = "SWE",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sweden",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c0f"),
                            Code = "UKR",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Ukraine",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c10"),
                            Code = "WAL",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Wales",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c11"),
                            Code = "KOR",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "South Korea",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c12"),
                            Code = "AUS",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Australia",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c13"),
                            Code = "AUT",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Austria",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c14"),
                            Code = "HUN",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Hungary",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c15"),
                            Code = "NOR",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Norway",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c16"),
                            Code = "CZE",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Czechia",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c17"),
                            Code = "NGA",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Nigeria",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c18"),
                            Code = "TUR",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Turkey",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c19"),
                            Code = "ECU",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Ecuador",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c1a"),
                            Code = "SCO",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Scotland",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c1b"),
                            Code = "GRE",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Greece",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c1c"),
                            Code = "TUN",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tunisia",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c1d"),
                            Code = "MLI",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Mali",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c1e"),
                            Code = "ALG",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Algeria",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c1f"),
                            Code = "EGY",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Egypt",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c20"),
                            Code = "CIV",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Ivory Coast",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c21"),
                            Code = "CAN",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Canada",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c22"),
                            Code = "SVK",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Slovakia",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c23"),
                            Code = "ROU",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Romania",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c24"),
                            Code = "CMR",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Cameroon",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c25"),
                            Code = "VEN",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Venezuela",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c26"),
                            Code = "PAR",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Paraguay",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f81d4fae-7dec-11d0-a765-00a0c91e6c27"),
                            Code = "SVN",
                            CreatedAt = new DateTime(2025, 6, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Slovenia",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("FutManagement.Core.Entities.PaymentInstallment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TransferId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TransferId");

                    b.ToTable("payment_installments", (string)null);
                });

            modelBuilder.Entity("FutManagement.Core.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MarketValue")
                        .HasColumnType("numeric");

                    b.Property<string>("MedicalStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("NationalityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nickname")
                        .HasColumnType("text");

                    b.Property<string>("PlayerStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("NationalityId");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("FutManagement.Core.Entities.Transfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DestinationClubId")
                        .HasColumnType("uuid");

                    b.Property<int>("NumberOfInstallments")
                        .HasColumnType("integer");

                    b.Property<Guid>("OriginClubId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TransferDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TransferValue")
                        .HasColumnType("numeric");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DestinationClubId");

                    b.HasIndex("OriginClubId");

                    b.HasIndex("PlayerId");

                    b.ToTable("transfers", (string)null);
                });

            modelBuilder.Entity("FutManagement.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0a0a0a0-a0a0-a0a0-a0a0-000000000001"),
                            CreatedAt = new DateTime(2025, 6, 28, 11, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@futmanagement.com",
                            FirstName = "Admin",
                            LastName = "User",
                            PasswordHash = "$2a$11$jcf3sC7CqV/kM2LzXbN5z.K.gYm2U.v9c.n.d.J9n.z9n.d.J9n.z",
                            Role = "Admin",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b0b0b0b0-b0b0-b0b0-b0b0-000000000002"),
                            CreatedAt = new DateTime(2025, 6, 28, 11, 0, 0, 0, DateTimeKind.Utc),
                            Email = "director@futmanagement.com",
                            FirstName = "Club",
                            LastName = "Director",
                            PasswordHash = "$2a$11$jcf3sC7CqV/kM2LzXbN5z.K.gYm2U.v9c.n.d.J9n.z9n.d.J9n.z",
                            Role = "ClubDirector",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c0c0c0c0-c0c0-c0c0-c0c0-000000000003"),
                            CreatedAt = new DateTime(2025, 6, 28, 11, 0, 0, 0, DateTimeKind.Utc),
                            Email = "agent@futmanagement.com",
                            FirstName = "Player",
                            LastName = "Agent",
                            PasswordHash = "$2a$11$jcf3sC7CqV/kM2LzXbN5z.K.gYm2U.v9c.n.d.J9n.z9n.d.J9n.z",
                            Role = "Agent",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("FutManagement.Core.Entities.Club", b =>
                {
                    b.HasOne("FutManagement.Core.Entities.Country", "Country")
                        .WithMany("Clubs")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("FutManagement.Core.Entities.PaymentInstallment", b =>
                {
                    b.HasOne("FutManagement.Core.Entities.Transfer", "Transfer")
                        .WithMany("Installments")
                        .HasForeignKey("TransferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transfer");
                });

            modelBuilder.Entity("FutManagement.Core.Entities.Player", b =>
                {
                    b.HasOne("FutManagement.Core.Entities.Club", "Club")
                        .WithMany("Players")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FutManagement.Core.Entities.Country", "Nationality")
                        .WithMany("Players")
                        .HasForeignKey("NationalityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Nationality");
                });

            modelBuilder.Entity("FutManagement.Core.Entities.Transfer", b =>
                {
                    b.HasOne("FutManagement.Core.Entities.Club", "DestinationClub")
                        .WithMany()
                        .HasForeignKey("DestinationClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FutManagement.Core.Entities.Club", "OriginClub")
                        .WithMany()
                        .HasForeignKey("OriginClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FutManagement.Core.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinationClub");

                    b.Navigation("OriginClub");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FutManagement.Core.Entities.Club", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("FutManagement.Core.Entities.Country", b =>
                {
                    b.Navigation("Clubs");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("FutManagement.Core.Entities.Transfer", b =>
                {
                    b.Navigation("Installments");
                });
#pragma warning restore 612, 618
        }
    }
}
